### ISSUE TITLE
Can not find The Full version

### ISSUE THREAD

**Issue by akihiro-komorilab** [Field-Robotics-Japan/OpenConstructionSimulator#14]
**Describe the bug**
README.md に記載されているThe Full versionのリンク先には何も存在しません。
ただし、GitHubのReleasesのリンク先にはリリース物が存在しています。 

**To Reproduce**
1. Go to https://github.com/Field-Robotics-Japan/OpenConstructionSimulator または https://github.com/Field-Robotics-Japan/OpenConstructionSimulator/blob/main/README.md 
2. Click on [The Full version](https://github.com/qoopen0815/OpenConstructionSimulator/releases)
3. There aren’t any releases here と表示される

**Expected behavior**
リンク先にリリースバージョンが表示される。

**Screenshots**
![image](https://github.com/Field-Robotics-Japan/OpenConstructionSimulator/assets/145914155/83ebcbf4-84c6-45fa-a2bc-5708c37644ba)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chrome
 - Version 119.0.6045.105

**Additional context**
リンクのURL が Field-Robotics-Japan と qoopen0815 とが混ざってしまっているようです。

**Comment by RyodoTanaka** [comment]
@akihiro-komorilab 
報告ありがとうございます。
https://github.com/Field-Robotics-Japan/OpenConstructionSimulator/pull/15

上記Pull Request にて該当箇所を修正しました。
