### ISSUE TITLE
Request to add collision for pipe

### ISSUE THREAD

**Issue by RyodoTanaka** [Field-Robotics-Japan/OpenConstructionSimulator#7]
Related to #6 , I request to add collision model for pipes, which merged on the PR.

#6 で言及している，パイプの衝突モデルの追加が必要なのでこちらにIssue建てておきます．

**Comment by qoopen0815** [comment]
対応しました

![image](https://user-images.githubusercontent.com/26988372/145670746-9b0389b7-353e-4e32-9458-9257bffa7d01.png)

**Comment by RyodoTanaka** [comment]
#8 の Approve コメントよりコピペ

素晴らしい！
さすが仕事が早いです

ちなみに，Collision 情報の追加はどうやって行いましたか？

**Comment by qoopen0815** [comment]
重機モデルのCollisionを追加したときとやり方は同じです。
複雑なモデルは複数のパーツに分割してCollisionメッシュとして登録すれば実装できます(`･ω･´)b

**Comment by RyodoTanaka** [comment]
なるほど！
ありがとうございますm(_ _)m

**Comment by RyodoTanaka** [comment]
希望の機能が実装されたので閉じます。
